Web/Areas/Admin/Controllers/ProductDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using Data.Models;
using Services;
using Microsoft.AspNetCore.Authorization;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductDetailsController : Controller
    {
        private readonly WebStoreDbContext _context;
        private readonly FileService _fileService;

        public ProductDetailsController(WebStoreDbContext context, FileService fileService)
        {
            _context = context;
            _fileService = fileService;
        }

        // GET: Admin/ProductDetails
        public async Task<IActionResult> Index()
        {
            var webStoreDbContext = _context.ChiTietSP.Include(c => c.SanPham);
            return View(await webStoreDbContext.ToListAsync());
        }

        // GET: Admin/ProductDetails/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chiTietSP = await _context.ChiTietSP
                .Include(c => c.SanPham)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chiTietSP == null)
            {
                return NotFound();
            }

            return View(chiTietSP);
        }

        // GET: Admin/ProductDetails/Create
        public IActionResult Create(int id)
        {
            if (_context.SanPham.Any(sp => sp.Id == id))
            {
                ViewData["ItemId"] = new SelectList(_context.SanPham.Where(sp => sp.Id == id), "Id", "Name");
                ViewData["MaSP"] = id;
            }
            else
            {
                return NotFound();
            }
            return View();
        }

        // POST: Admin/ProductDetails/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,Quantity,Unit,Price,Name,Note,ImageFile")] ChiTietSP chiTietSP)
        {
            if (chiTietSP.ImageFile != null)
            {
                chiTietSP.ImageName = await _fileService.Upload(chiTietSP.ImageFile);
            }

            if (ModelState.IsValid)
            {
                _context.Add(chiTietSP);
                await _context.SaveChangesAsync();
                var sanPham = _context.SanPham.FirstOrDefault(sp => sp.Id == chiTietSP.ItemId);
                var priceQuery = from detail in _context.ChiTietSP
                                 where detail.ItemId == chiTietSP.ItemId
                                 select detail.Price;
                sanPham.Quantity += chiTietSP.Quantity;
                var price = priceQuery.ToList();
                sanPham.OptionCount++;
                sanPham.MinPrice = 0;
                price.GetMinMax((min, max) =>
                {
                    sanPham.MinPrice = min;
                    sanPham.MaxPrice = max;
                });
                sanPham.DefaultDetailId = _context.ChiTietSP.FirstOrDefault(sp => sp.Price == sanPham.MinPrice && sp.ItemId == sanPham.Id)?.Id;
                await _context.SaveChangesAsync();
                return Redirect(Url.Action(nameof(ProductsController.Details), "Products", new { id = chiTietSP.ItemId }));
            }
            ViewData["ItemId"] = new SelectList(_context.SanPham, "Id", "Name", chiTietSP.ItemId);
            return View(chiTietSP);
        }

        // GET: Admin/ProductDetails/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chiTietSP = await _context.ChiTietSP.FindAsync(id);
            if (chiTietSP == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.SanPham, "Id", "Name", chiTietSP.ItemId);
            return View(chiTietSP);
        }

        // POST: Admin/ProductDetails/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ItemId,Quantity,Unit,AverateReceiptPrice,Sold,Price,Name,Note,ImageFile,Id")] ChiTietSP chiTietSP)
        {
            if (id != chiTietSP.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var old = _context.ChiTietSP.AsNoTracking().SingleOrDefault(ct => ct.Id == id);
                    chiTietSP.ImageName = old.ImageName;
                    var sanPham = _context.SanPham.FirstOrDefault(sp => sp.Id == chiTietSP.ItemId);
                    sanPham.Quantity -= old.Quantity;
                    sanPham.Quantity += chiTietSP.Quantity;
                    chiTietSP.SanPham = sanPham;
                    _context.Update(chiTietSP);
                    await _context.SaveChangesAsync();
                    var priceQuery = from detail in _context.ChiTietSP
                                     where detail.ItemId == chiTietSP.ItemId
                                     select detail.Price;
                    var price = priceQuery.ToList();
                    sanPham.MinPrice = 0;
                    price.GetMinMax((min, max) =>
                    {
                        sanPham.MinPrice = min;
                        sanPham.MaxPrice = max;
                    });
                    sanPham.DefaultDetailId = _context.ChiTietSP.FirstOrDefault(sp => sp.Price == sanPham.MinPrice && sp.ItemId == sanPham.Id)?.Id;
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ChiTietSPExists(chiTietSP.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Redirect(Url.Action(nameof(ProductsController.Details), "Products", new { id = chiTietSP.ItemId }));
            }
            ViewData["ItemId"] = new SelectList(_context.SanPham, "Id", "Name", chiTietSP.ItemId);
            return View(chiTietSP);
        }

        // GET: Admin/ProductDetails/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chiTietSP = await _context.ChiTietSP
                .Include(c => c.SanPham)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (chiTietSP == null)
            {
                return NotFound();
            }

            return View(chiTietSP);
        }

        // POST: Admin/ProductDetails/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chiTietSP = await _context.ChiTietSP.FindAsync(id);
            _context.ChiTietSP.Remove(chiTietSP);
            await _context.SaveChangesAsync();
            var sanPham = _context.SanPham.FirstOrDefault(sp => sp.Id == chiTietSP.ItemId);
            var priceQuery = from detail in _context.ChiTietSP
                             where detail.ItemId == chiTietSP.ItemId
                             select detail.Price;
            var price = priceQuery.ToList();
            sanPham.MinPrice = 0;
            sanPham.OptionCount--;
            price.GetMinMax((min, max) =>
            {
                sanPham.MinPrice = min;
                sanPham.MaxPrice = max;
            });
            sanPham.Quantity -= chiTietSP.Quantity;
            sanPham.DefaultDetailId = _context.ChiTietSP.FirstOrDefault(sp => sp.Price == sanPham.MinPrice && sp.ItemId == sanPham.Id)?.Id;
            await _context.SaveChangesAsync();
            return Redirect(Url.Action(nameof(ProductsController.Details), "Products", new { id = chiTietSP.ItemId }));
        }

        private bool ChiTietSPExists(int id)
        {
            return _context.ChiTietSP.Any(e => e.Id == id);
        }
    }
}

Web/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Data;
using Data.Models;
using Services;
using Microsoft.AspNetCore.Authorization;

namespace Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductsController : Controller
    {
        private readonly WebStoreDbContext _context;
        private readonly FileService _fileService;

        public ProductsController(WebStoreDbContext context, FileService fileService)
        {
            _context = context;
            _fileService = fileService;
        }

        // GET: Admin/Products
        public async Task<IActionResult> Index()
        {
            int page = 1;
            if (HttpContext.Request.Query.ContainsKey("page")) int.TryParse(HttpContext.Request.Query["page"], out page);
            var webStoreDbContext = _context.SanPham.Skip(page*10-10).Take(page*10).Include(s => s.Category);
            ViewData["TotalRecord"] = await _context.SanPham.CountAsync();
            return View(await webStoreDbContext.ToListAsync());
        }

        // GET: Admin/Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham
                .Include(s => s.Category)
                .Include(s => s.Details)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["MaSP"] = sanPham.Id;
            return View(sanPham);
        }

        // GET: Admin/Products/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.LoaiSP, "Id", "Name");
            return View();
        }

        // POST: Admin/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,CategoryId,ShowAtHome,OptionName,MainImageFile,Quantity,MinPrice,MaxPrice,OptionCount,Sold,Description,KeyWord,DefaultDetailId,Id")] SanPham sanPham)
        {
            if (sanPham.MainImageFile != null)
            {
                sanPham.MainImageName = await _fileService.Upload(sanPham.MainImageFile);
            }
            if (ModelState.IsValid)
            {
                _context.Add(sanPham);
                await _context.SaveChangesAsync();
                var loaiSP = await _context.LoaiSP.FirstOrDefaultAsync(lsp => lsp.Id == sanPham.CategoryId);
                if (loaiSP != null)
                {
                    loaiSP.ItemsCount = _context.SanPham.Count(sp => sp.CategoryId == loaiSP.Id);
                    await _context.SaveChangesAsync();
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.LoaiSP, "Id", "Name", sanPham.CategoryId);
            return View(sanPham);
        }

        // GET: Admin/Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham.FindAsync(id);
            if (sanPham == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.LoaiSP, "Id", "Name", sanPham.CategoryId);
            return View(sanPham);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,CategoryId,ShowAtHome,OptionName,MainImageFile,Quantity,MinPrice,MaxPrice,OptionCount,Sold,Description,KeyWord,DefaultDetailId,Id")] SanPham sanPham)
        {
            var old = await _context.SanPham.AsNoTracking().FirstOrDefaultAsync(sp => sp.Id == id);
            sanPham.MainImageName = old.MainImageName;
            if (id != sanPham.Id)
            {
                return NotFound();
            }
            if (sanPham.MainImageFile != null)
            {
                sanPham.MainImageName = await _fileService.Upload(sanPham.MainImageFile);
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sanPham);
                    await _context.SaveChangesAsync();
                    var loaiSP = await _context.LoaiSP.FirstOrDefaultAsync(lsp => lsp.Id == sanPham.CategoryId);
                    if (loaiSP != null)
                    {
                        loaiSP.ItemsCount = _context.SanPham.Count(sp => sp.CategoryId == loaiSP.Id);
                        await _context.SaveChangesAsync();
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SanPhamExists(sanPham.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.LoaiSP, "Id", "Name", sanPham.CategoryId);
            return View(sanPham);
        }

        // GET: Admin/Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sanPham = await _context.SanPham
                .Include(s => s.Category)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (sanPham == null)
            {
                return NotFound();
            }

            return View(sanPham);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sanPham = await _context.SanPham.FindAsync(id);
            _context.SanPham.Remove(sanPham);
            await _context.SaveChangesAsync();
            var loaiSP = await _context.LoaiSP.FirstOrDefaultAsync(lsp => lsp.Id == sanPham.CategoryId);
            if (loaiSP != null)
            {
                loaiSP.ItemsCount = _context.SanPham.Count(sp => sp.CategoryId == loaiSP.Id);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool SanPhamExists(int id)
        {
            return _context.SanPham.Any(e => e.Id == id);
        }
    }
}

Web/Areas/Admin/Views/Products/Create.cshtml
@model Data.Models.SanPham

@{
    ViewData["Title"] = "Thêm sản phẩm";
}

<h1>Tạo mới</h1>

<h4>Sản phẩm</h4>
<hr />
<div>
    <div>
        <form class="row" asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="OptionName" class="control-label"></label>
                <input asp-for="OptionName" class="form-control" />
                <span asp-validation-for="OptionName" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="MainImageFile" class="control-label"></label>
                <input asp-for="MainImageFile" class="form-control" />
                <span asp-validation-for="MainImageFile" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="Description" class="control-label"></label>
                <textarea id="editor" asp-for="Description" class="form-control" ></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="KeyWord" class="control-label"></label>
                <input asp-for="KeyWord" class="form-control" />
                <span asp-validation-for="KeyWord" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <input type="submit" value="Thêm" class="btn btn-primary" />
                <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var ckeditor;
        $(function () {
            CKEDITOR.replace("editor");
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Areas/Admin/Views/Products/Delete.cshtml
@model Data.Models.SanPham

@{
    ViewData["Title"] = "Xóa sản phẩm";
}

<h1>Xóa sẩn phẩm</h1>

<h3>Bạn có chắc chắn muốn xóa sản phẩm này?</h3>
<div>
    <h4>SanPham</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Category.Name)
        </dd class>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.ShowAtHome)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.ShowAtHome)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.OptionName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.OptionName)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.MainImageName)
        </dt>
        <dd class="col-sm-8">
            <img height="100" src="/api/file/@Model.MainImageName" />
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.MinPrice)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.MinPrice)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.MaxPrice)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.MaxPrice)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.OptionCount)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.OptionCount)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Sold)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Sold)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.KeyWord)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.KeyWord)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Xác nhận xóa" class="btn btn-danger" />
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Areas/Admin/Views/Products/Details.cshtml
@model Data.Models.SanPham

@{
    ViewData["Title"] = "Chi tiết sản phẩm";
    ViewData["MaSP"] = Model.Id.ToString();
}

<h1>Chi tiết</h1>

<div>
    <h4>Sản phẩm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.ShowAtHome)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.ShowAtHome)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.OptionName)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.OptionName)
        </dd>
        <dt class="col-sm-4">
            @Html.DisplayNameFor(model => model.MainImageName)
        </dt>
        <dd class="col-sm-8">
            <img height="100" src="/api/file/@Model.MainImageName" />
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.MinPrice)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.MinPrice)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.MaxPrice)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.MaxPrice)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.OptionCount)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.OptionCount)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.Sold)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.Sold)
        </dd>
        <dt class = "col-sm-12">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-12">
            @Html.Raw(@Model.Description)
        </dd>
        <dt class = "col-sm-4">
            @Html.DisplayNameFor(model => model.KeyWord)
        </dt>
        <dd class = "col-sm-8">
            @Html.DisplayFor(model => model.KeyWord)
        </dd>
        <dt class="col-12">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class="col-12">
            @await Html.PartialAsync("_DSChiTietSP", Model.Details, ViewData)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-info" asp-action="Edit" asp-route-id="@Model.Id">Chỉnh sửa</a>
    <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách</a>
</div>

Web/Areas/Admin/Views/Products/Edit.cshtml
@model Data.Models.SanPham

@{
    ViewData["Title"] = "Chỉnh sửa sản phẩm";
}

<h1>Chỉnh sửa</h1>

<h4>Sản phẩm</h4>
<hr />
<div>
    <div>
        <form class="row" asp-action="Edit"  enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="OptionName" class="control-label"></label>
                <input asp-for="OptionName" class="form-control" />
                <span asp-validation-for="OptionName" class="text-danger"></span>
            </div>
            <div class="form-group col-12 col-md-6">
                <label asp-for="MainImageFile" class="control-label"></label>
                <input asp-for="MainImageFile" class="form-control" />
                <span asp-validation-for="MainImageFile" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="Description" class="control-label"></label>
                <textarea id="editor" asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <label asp-for="KeyWord" class="control-label"></label>
                <input asp-for="KeyWord" class="form-control" />
                <span asp-validation-for="KeyWord" class="text-danger"></span>
            </div>
            <div class="form-group col-12">
                <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
                <a class="btn btn-outline-primary" asp-action="Index">Quay lại danh sách</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        var ckeditor;
        $(function () {
            CKEDITOR.replace("editor");
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Areas/Admin/Views/Products/_DSChiTietSP.cshtml
@model IEnumerable<Data.Models.ChiTietSP>
@{
    string MaSP = ViewData["MaSP"] as string;
}

<p>
    <a asp-action="Create" asp-controller="ProductDetails" asp-route-id="@MaSP">Thêm chi tiết</a>
</p>
<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sold)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Note)
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img height="50" src="/api/file/@item.ImageName" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sold)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Note)
                </td>
            <td class="d-flex">
                <a title="Chỉnh sửa" class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id"><i class="far fa-edit"></i></a>
                <a title="Chi tiết" class="mx-1 btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id"><i class="fas fa-info"></i></a>
                <a title="Xóa" class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.Id"><i class="far fa-trash-alt"></i></a>
            </td>
            </tr>
        }
    </tbody>
</table>